src/entities/Party.ts, src/entities/index.ts, src/screens/HomeScreen.tsx, src/screens/PostScreen.tsx, src/services/party.ts
=> fetchThumbnailURLVer2 （再度ブランチを切ったfetchThumbnailURL）

package.json, src/components/organisms/UploadCertificateModal.tsx, src/components/organisms/index.ts, src/entities/User.ts, src/repositories/index.ts, src/repositories/secure.ts, src/repositories/user.ts, src/screens/UserEditScreen.tsx, src/screens/UserScreen.tsx, src/services/secure.ts, yarn.lock
=> 身分証提出の導線作成

src/components/atoms/TextBox.tsx, src/components/atoms/index.ts, src/components/organisms/UserListItem.tsx, src/components/organisms/index.ts, src/components/pages/SearchUserPage.tsx, src/components/pages/index.ts, src/components/templates/FullScreenModal.tsx, src/components/templates/index.ts, src/services/design/android.ts, src/services/design/index.ts, src/services/design/ios.ts, src/services/user.ts
=> ユーザー検索モーダル作成

src/screens/UserEditScreen.tsx, src/screens/UserScreen.tsx, src/themes/colors.ts
=> ユーザー画面のデザイン変更

src/components/atoms/Thumbnail.tsx, src/components/organisms/UserListItem.tsx, src/components/pages/SearchUserPage.tsx, src/entities/User.ts, src/screens/UserScreen.tsx, src/services/user.ts
=> userIDを表示するように変更

src/entities/User.ts, src/repositories/firebase/index.ts, src/repositories/user.ts, src/screens/UserEditScreen.tsx, src/services/user.ts
=> userID変更機能追加

src/navigators/TabNavigator.tsx, src/screens/HomeScreen.tsx, src/screens/PartyDetailScreen.tsx, src/screens/PartyEntryScreen.tsx, src/screens/PostScreen.tsx, src/screens/PrivacyScreen.tsx, src/screens/TermsScreen.tsx, src/screens/UserEditScreen.tsx, src/screens/UserScreen.tsx, src/screens/WelcomeScreen.tsx, src/themes/colors.ts
=> ダークモードベースにアプリカラー変更

src/screens/PartyDetailScreen.tsx
参加完了した後，参加完了画面を出して，その後”Homeに戻る”ボタンを作成後，Homeに戻るって流れで良いですか？
=> PartyDetailScreenからEntryPartyScreenに遷移して参加申請

src/actions/auth.ts, src/reducers/auth.ts, src/sagas/auth.ts
これで自身のUser情報取得できるようになるので、genderチェックはこの値を読みに行くようにしてほしい。
=> 認証時、ユーザー情報を取得する機能追加

.circleci/config.yml
=> expo publishのjob追加

.circleci/config.yml
=> feat: edit publish cmd

src/components/pages/ChatroomPage/Actions.tsx, src/components/pages/ChatroomPage/Avatar.tsx, src/components/pages/ChatroomPage/Bubble.tsx, src/components/pages/ChatroomPage/Composer.tsx, src/components/pages/ChatroomPage/Day.tsx, src/components/pages/ChatroomPage/InputToolbar.tsx, src/components/pages/ChatroomPage/Send.tsx, src/components/pages/ChatroomPage/index.tsx, src/components/pages/index.ts, src/screens/ChatScreen.tsx, src/services/chat.ts, src/services/design/style.ts, src/store/configureSaga.ts, src/store/ui/actions.ts, src/store/ui/index.ts, src/store/ui/reducer.ts, src/store/ui/saga.ts
=> トークルームのスタイリング修正

App.tsx, src/screens/HomeScreen.tsx, src/services/party.ts, src/store/configureSaga.ts, src/store/hooks.ts, src/store/room/actions.ts, src/store/room/index.ts, src/store/room/saga.ts
expoアプリの初期起動時固まるバグの原因が、entryDemoPartyの発火周りであることがわかった。
なので、バグを消しながら、別プロセスに切り出す。
=> entryDemoPartyの非同期プロセスの切り出し

src/components/atoms/AddFab.tsx, src/screens/PartyGroupsScreen.tsx, src/services/flashCard.ts, src/services/groups.ts
既に飲み会を作成している人がさらにAddFab押して作成しようとすると，FlashCardでwarningが出るようにしました．
=> addFabのstyle修正&groupの２重作成に対するアクション追加

src/repositories/friend.ts
一部firendUsersからfriendsへ変更できていなかった部分があるため修正します．
=> firendUsersからfriendsへの修正

app.json
app.jsonにパラメーター追加しただけなので、レビューなしでマージする。
=> bundleID追加

src/components/organisms/PartyPrimaryCard.tsx, src/components/organisms/PartySecondaryCard.tsx, src/themes/normal.ts
デザインのみ少し修正しただけなので、レビューなしでマージします。
=> Partyカードの細かいデザイン修正

src/components/atoms/RoundedButton.tsx, src/components/organisms/Modal.tsx, src/screens/HomeScreen.tsx
=> モーダルコンポーネントのデザイン修正

src/components/atoms/TextInput.tsx, src/components/moleculers/SelectField.tsx, src/components/moleculers/TextField.tsx, src/components/moleculers/index.ts, src/components/organisms/PartyPrimaryCard.tsx, src/components/organisms/PartySecondaryCard.tsx, src/components/organisms/RoomCard.tsx, src/screens/UserEditScreen.tsx, src/themes/normal.ts
作成したコンポーネント
TextField
SelectField
=> テキストインプット周りのコンポーネント作成

src/repositories/appliedCard.ts, src/screens/SwipeCardScreen.tsx
likeApplyCardが連打できる仕様だったので、同じファンクションが数ミリ感覚で実行されたためファデータが重複しないかのチェックをすり抜けたのだと思われる。
前からしようと思っていたカードをキャッシュ化でここら辺解決できるのでキャッシュ化させた。
=> カードをキャッシュさせてLikeさせるように変更

src/screens/UserScreen.tsx
=> ユーザー画面を最新のデザインに修正と空メッセージ追加

src/screens/RoomScreen.tsx, src/screens/UserScreen.tsx, src/themes/normal.ts
=> ルーム画面に空メッセージ追加

src/components/organisms/RoomCard.tsx, src/screens/ChatScreen.tsx
=> チャット画面に空メッセージ追加

src/screens/SwipeCardScreen.tsx
=> スワイプ画面に空メッセージ追加
